// <auto-generated />
namespace CarShowroom.Entities.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class delete_name_column_from_Client : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(delete_name_column_from_Client));
        
        string IMigrationMetadata.Id
        {
            get { return "202104281629307_delete_name_column_from_Client"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
