// <auto-generated />
namespace CarShowroom.Entities.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Editing_resolution_entity_model : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Editing_resolution_entity_model));
        
        string IMigrationMetadata.Id
        {
            get { return "202105092124080_Editing_resolution_entity_model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
