// <auto-generated />
namespace CarShowroom.Entities.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Initializedatabase : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Initializedatabase));
        
        string IMigrationMetadata.Id
        {
            get { return "202104091515594_Initialize database"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
